### ISSUE TITLE
Celestia mobi crashing

### ISSUE THREAD

**Issue by SpaceExplorer2008** [levinli303/celestia.mobi#34]
I don't know if we can consider this a problem, so there is one thing that is quite annoying on the mobi: Celestia crashing and the app freezing. For example, if I activate in the settings "high resolution textures", I just see the Saturn system, for example, and Celestia will crash. I always have to keep medium resolution.

And this is also bad with add-ons that use a high number of textures or high resolution. There are some that shouldn't even be possible to use on slower smartphones. My smartphone has 2 GB of RAM, but it seems to need 8-16 GB of RAM to keep it from crashing.

Other astronomical apps may have high resolution textures, but they don't crash. Can this problem be solved or avoided in mobi?

**Comment by levinli303** [comment]
The reason why it crashes is most likely due to memory constraint, and this has to be fixed in upstream Celestia repo (via error handling when memory allocation fails, but unlikely to happen because Celestia was never written for device with memory constraint,  to do it, you would need to rewrite almost everything), not on any specific frontend.

I've seen quite a few crashes on Android in the crash reporting system, however the logs are not helpful to understand for what reason Celestia crashed, and I assume they are about memory constraint. Some are listed here https://github.com/levinli303/AndroidCelestia/issues/17 . If you could provide system logs around the time Celestia crashed, then it will help us understand it happens. to get system log, there is a guide here https://support.esri.com/en/technical-article/000017058
