### ISSUE TITLE
It is no longer possible to use two or more addons in Celestia Mobile

### ISSUE THREAD

**Issue by SpaceExplorer2008** [levinli303/celestia.mobi#43]
A recent issue appeared in Celestia Mobile after the last update. It is not possible to use two or more add-ons to customize a celestial body. For example, already uploaded to GitHub is an addon that adds a new surface and night map of Earth. But with that, if together I use a separate cloud map, for example the one from the Earth addon (1972), the new night map simply disappears. Earth is without a night map. Before the latest update, everything was working normally.

@SevenSpheres considers it likely to be a bug.

**Comment by SevenSpheres** [comment]
Clarification: the issue originally reported was with [this addon that adds an aurora to Jupiter](https://celestia.mobi/resources/item?item=E5E1A4EA-EE26-E97A-F7DC-949ADA42B099) and [this addon that modifies its rings](https://celestia.mobi/resources/item?item=368E4CAC-8C67-4351-454B-1E6BDF416BAF). When both of these addons are used together with the rings loading after the aurora, the aurora (defined as a night texture) isn't shown. This happens on Celestia 1.7 (desktop) but not on 1.6, so it's clearly a bug. (Seeing the addon IDs, it actually looks like there *shouldn't* be a problem on mobile since the ring addon should load first.)

Given that and the issue reported here, the issue appears to be that any modification to an object causes any previously defined night texture to disappear, not that it's not possible to use multiple addons modifying the same object.

**Comment by DaveBowman2001** [comment]
I can't recreate the bug on the following add-ons that modify the same object below:

Jupiter Auroras and Jupiter Rings
![Screenshot_20221114-105246](https://user-images.githubusercontent.com/95486841/201565852-7c183e03-f45b-41d7-94bd-ee2f024d0fd8.png)

Earth Auroras and Earth (1972)
![Screenshot_20221114-105658](https://user-images.githubusercontent.com/95486841/201565894-ba20c2ec-d0cb-433c-bc49-b16d34ecb1ed.png)

Io Night and Io (Volcanic Plumes)
![Screenshot_20221114-105745](https://user-images.githubusercontent.com/95486841/201565935-160e5c44-3539-458e-a77a-0f944a6f0a66.png)

They all seem fine to me so far

**Comment by DaveBowman2001** [comment]
Huh...weird I take it back for the case of Earth (1972). The night texture does disappear for some reason, where only the clouds should be the only ones changed

**Comment by SpaceExplorer2008** [comment]
Two potential workarounds: 

1) Remove the addon Earth (1972) 

2) Adapt the cloud texture with another addon, for example the recently uploaded [Earth](https://celestia.mobi/resources/item?item=5338AEF4-EA7E-49C8-A4D0-FF1297F8182F). I tested this and it worked.

**Comment by DaveBowman2001** [comment]
Even so, it shouldn't affect the default night texture in the first place as Earth (1972) only changes the clouds. Will take another look and possibly upload an SSC patch if I found the cause
